name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🏗 Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: 📦 Cache tools
        uses: actions/cache@v4
        with:
          path: bin
          key: ${{ runner.os }}-tools-${{ hashFiles('scripts/*.sh') }}

      - name: 🔧 Make scripts executable
        run: chmod +x scripts/*.sh

      - name: 📦 Install test tools
        run: ./scripts/install_tparse.sh

      - name: 🧪 Run tests
        run: ./scripts/test.sh